product/urls.py
from django.urls import path

app_name='product'
from .views import product_create_view, register_view, product_detail_view, user_view, login_user, logout_user,product_update_view, product_delete_view, like_post

urlpatterns = [
        path('create/', product_create_view, name='product-create'),
        path('register/', register_view, name='register-user'),
        path('login/', login_user, name='login-user'),
        path('logout/', logout_user, name='logout-user'),
        path('<int:pk>/', product_detail_view, name='product-detail'),
        path('user/', user_view, name='user-view'),
        path('update/<int:pk>/', product_update_view, name='product-update'),
        path('delete/<int:pk>/', product_delete_view, name='product-delete'),
        path('like/', like_post, name='like-post'),


        # path('comment/', product_comment_view, name='product-comment'),



]

website/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from product.views import home_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('', home_view, name='home-view'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>hello</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300&display=swap" rel="stylesheet">
    <style media="screen">
    * {
        margin: 0;
        padding: 0;
        border: 0;
        font-family: 'Oswald', sans-serif;

    }
    html {
        font-family: 'Oswald', sans-serif;
          background: rgb(199, 208, 210);

        }

    body {
          margin: 0;
          padding: 0;
        }

    nav a {
          text-decoration: None;
          color: white
        }

    a:hover {
          color: red
        }
    </style>
  </head>
  <body>
    {% include 'navbar.html' %}
    {% block content %}
    change
    {% endblock %}
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1>Hello</h1>
{% for instance in product %}

  <p><a href="{{ instance.get_absolute_url}}">{{ instance.id }}</a> - {{ instance.prodname }} - {{ instance.description }} - {{ instance.price }} - <img src="{{ instance.image.url}}" width="10%" height="10%"> -   {{ instance.creator }}</p>
<form class="" action="{% url 'product:like-post' %}" method="post">{% csrf_token %}
<input type="hidden" name="product_id" value="{{instance.id}}">
{% if user not in instance.likes.all %}
<button type="submit" name="button">Like</button>
{% else %}
<button type="submit" name="button">Unlike</button>

{% endif %}
</form>
<strong>{{ instance.likes.all.count }} likes</strong>


{% endfor %}
{% endblock %}
<!-- <table>
  <tr>
    <td>{{ instance.creator }}</td>
    <td>{{ instance.prodname }}</td>
    <td>{{ instance.description }}</td>
    <td>{{ instance.price }}</td>
    <td><img src="{{ instance.image.url}}" width="10%" height="10%"></td>
    <a href="{{ instance.get_absolute_url}}">{{ instance.id }}</a>

  <tr>
<table> -->

templates/navbar.html
<style media="screen">

nav {
  margin: 0;
  padding: 0;
  height: 150px;
  border-style: solid black;
  font-family: 'Oswald', sans-serif;
  background: rgb(57, 57, 58);
  text-color: red
  position: relative
}
.test-1{
  text-align: left;
  line-height:40px;
  margin-left: 10px;
}
ul {
  list-style: none

}
li:hover {
    color:red;
}
.prof-right {
  text-align: right

}
</style>
<nav>
<div class="test-1">

<ul>
  <a href="{% url 'home-view' %}"><li>Home</li></a>
  <a href="#"><li>About</li></a>
  <a href="#"><li>Contact</li></a>

</ul>
</div>
<div class="prof-right">
<span><a href="{% url 'product:user-view' %}">My user profile</a></span>
<span><a href="{% url 'product:register-user' %}">Register</a></span>
<span><a href="{% url 'product:login-user' %}">Login</a></span>
<span><a href="{% url 'product:logout-user' %}">Logout</a></span>
</div>

</nav>

templates/user.html
{% extends 'base.html' %}


{% block content %}
<h1>hello, {{ user.username }}</h1>
<span><a href="{% url 'product:product-create' %}">Create a product</a></span>
<br>

{% for instance in product %}
<p>
    <!--allows us to update each of the product -->
   <li><a href="{% url 'product:product-update' instance.pk %}">update</a></li>
   <li><a href="{% url 'product:product-delete' instance.pk %}">delete</a></li>

  {{ instance.creator }}
  {{ instance.prodname }}
  {{ instance.description }}
  {{ instance.price }}
<img src="{{ instance.image.url }}" width="10%" height="10%"></p>
{% endfor %}
{% endblock %}